export enum RouteBasedEnum {
    Overview = "overview",
    OverviewSite = "overview#site-overview",
    OverviewInstructions = "overview#instructions",
    OverviewSchedule = "overview#schedule",
    OverviewKeyTerms = "overview#key-term-and-definitions",
    FloodRiskExisting = "floodrisk-existing",
    FloodRiskFuture = "floodrisk-future",
    SolutionsFMP = "solutions-fmp",
    SolutionsFME = "solutions-fme",
    SolutionsFMS = "solutions-fms",
    Infrastructure = "infrastructure",
    PFMgnt = "floodplain-managment",
    MapData = "mapdata",
    Resource = "resource",
    ResourceReport = "resource#report",
    ResourceLinks = "resource#links",
    ResourceInvolved = "resource#involved",
    ResourceImplementation = "resource#implementation",
    ResourcePolicy = "resource#policy",
    Feedback = "feedback",
    Contact = "contact",
    FAQs = "faqs",
}